Repository 2110336-SoftwareEngineering2/sec33_Kojira, pull requests merged in 2021-03, with the labels that each got.

#60 Front-end Nont owner dashboard (dummy)
  nontclient/public/no-image.svg
  nontclient/src/Components/Dashboard/Dashboard.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/LoadingReservation.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/NontOwnerDashboard.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/NontOwnerDashboard.module.css
  nontclient/src/Components/Dashboard/NontOwnerDashboard/ReservationList.js
  nontclient/src/Components/Dashboard/NontSitterDashboard/NontSitterDashboard.js
  nontclient/src/Components/FindShelter/FindShelter.module.css
  nontclient/src/Components/FindShelter/ShelterCard.js
  nontclient/src/Services/ReserveService.js
Labels: enhancement, front end

#65 Add image in find shelter page
  nontclient/src/Components/FindShelter/FindShelter.module.css
  nontclient/src/Components/FindShelter/ShelterCard.js
Labels: enhancement, front end

#66 Update Shelter Cards' link in Find Shelter
  nontclient/src/Components/FindShelter/ShelterCard.js
  nontclient/src/Components/FindShelter/StarRating.js
  nontclient/src/Router/NontSitterRouter.js
  nontclient/src/Router/mainRouter.js
Labels: front end

#79 Implement Nont owner dashboard with real data
  nontclient/package-lock.json
  nontclient/src/Components/Dashboard/NontOwnerDashboard/LoadingReservation.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/NontOwnerDashboard.module.css
  nontclient/src/Components/Dashboard/NontOwnerDashboard/ReservationHistory.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/ReservationList.js
  nontclient/src/Components/Shelter/ShelterView.js
  nontclient/src/Constants/ReservationStatus.js
  nontclient/src/Services/ReserveService.js
  nontclient/yarn.lock
  nontserver/yarn.lock
Labels: front end, update

#85 Add bottom padding
  nontclient/src/App.js
  nontclient/src/Components/Reservation/Reserve.js
  nontclient/src/index.css
Labels: fix, front end, update

#86 backend review layout and create review
  nontserver/Controllers/ReviewController.js
  nontserver/Models/Review.js
  nontserver/routes/index.js
  nontserver/routes/review.js
Labels: back end

#87 Add Loading component
  nontclient/src/App.js
  nontclient/src/App.module.css
  nontclient/src/Components/Dashboard/NontOwnerDashboard/LoadingReservation.js
  nontclient/src/Components/Dashboard/NontOwnerDashboard/NontOwnerDashboard.module.css
  nontclient/src/Components/FindShelter/FindShelter.js
  nontclient/src/Components/Shared/Loading.js
  nontclient/src/Components/Shared/Loading.module.css
Labels: front end

#91 review backend
  nontserver/Controllers/ReviewController.js
  nontserver/Controllers/RoomController.js
  nontserver/Controllers/ShelterController.js
  nontserver/routes/review.js
Labels: back end
