Repository 2110336-SoftwareEngineering2/sec33_Kojira, pull requests merged in 2021-04, with the labels that each got.

#92 add Loading screen to RoomManage, ShelterManage
  nontclient/src/Components/Nont/NontManage.js
  nontclient/src/Components/Nont/NontView.js
  nontclient/src/Components/Room/RoomManage.js
  nontclient/src/Components/Shelter/ShelterManage.js
  nontclient/src/Components/Shelter/ShelterView.js
Labels: front end

#97 [front end] add InfoDB and SelectDB
  nontclient/src/Components/Admin/InfoDB.js
  nontclient/src/Components/Admin/SelectDB.js
  nontclient/src/Components/NavigationBar/NavigationBar.js
  nontclient/src/Components/NavigationBar/NavigationItems/NavigationLeftLinks.js
  nontclient/src/Components/Room/RoomManage.js
  nontclient/src/Components/Shared/Loading.js
  nontclient/src/Router/AdminRouter.js
  nontclient/src/Router/mainRouter.js
  nontclient/src/Services/AdminService.js
  nontserver/Controllers/ReservationController.js
  nontserver/routes/reservation.js
Labels: front end

#102 InfoDB almost complete
  nontclient/src/Components/Admin/InfoDB.js
  nontclient/src/Config/serverURL.js
  nontserver/Controllers/NontOwnerController.js
  nontserver/Controllers/ShelterController.js
Labels: front end

#107 Add filtering, sorting and pagination in Find shelter
  nontclient/src/Components/FindShelter/FindShelter.js
  nontclient/src/Components/FindShelter/FindShelter.module.css
  nontclient/src/Components/FindShelter/FindShelterList.js
  nontclient/src/Components/FindShelter/ShelterCard.js
  nontclient/src/Components/FindShelter/ShelterFilter/DistanceFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/NontAmountFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/NontTypeFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/PriceFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/RatingFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/ShelterFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/ShelterSearch.js
  nontclient/src/Components/FindShelter/ShelterSort.js
  nontclient/src/Services/ShelterService.js
  nontserver/Controllers/ShelterController.js
  nontserver/package.json
  nontserver/routes/shelters.js
  nontserver/yarn.lock
Labels: back end, front end, new feature

#106 correct term cancel, delete, remove
  nontclient/src/Components/Nont/NontManage.js
  nontclient/src/Components/Reservation/Review.js
  nontclient/src/Config/serverURL.js
  nontclient/src/Services/NontService.js
  nontclient/src/Services/ReserveService.js
  nontclient/src/Services/ReviewService.js
  nontclient/src/Services/RoomService.js
  nontclient/src/Services/ShelterService.js
  nontserver/Controllers/NontController.js
  nontserver/Controllers/NontOwnerController.js
  nontserver/Controllers/NontSitterController.js
  nontserver/Controllers/ReservationController.js
  nontserver/Controllers/ReviewController.js
  nontserver/Controllers/RoomController.js
  nontserver/Controllers/ShelterController.js
  nontserver/routes/nont.js
  nontserver/routes/nontOwners.js
  nontserver/routes/nontSitters.js
  nontserver/routes/reservation.js
  nontserver/routes/review.js
  nontserver/routes/room.js
  nontserver/routes/shelters.js
Labels: back end, front end

#110 Cascade Remove
  nontclient/src/Components/Admin/InfoDB.js
  nontclient/src/Services/AdminService.js
  nontserver/Controllers/ReservationController.js
  nontserver/Controllers/ReviewController.js
  nontserver/Models/Nont.js
  nontserver/Models/NontOwner.js
  nontserver/Models/NontSitter.js
  nontserver/Models/Reservation.js
  nontserver/Models/Room.js
  nontserver/Models/Shelters.js
  nontserver/routes/shelters.js
Labels: back end

#114 [backend] implement OOP
  nontserver/Controllers/InterfaceController.js
  nontserver/Controllers/NontController.js
  nontserver/Controllers/NontOwnerController.js
  nontserver/Controllers/NontSitterController.js
  nontserver/Controllers/ReservationController.js
  nontserver/Controllers/ReviewController.js
  nontserver/Controllers/RoomController.js
  nontserver/Controllers/ShelterController.js
  nontserver/routes/nont.js
  nontserver/routes/nontOwners.js
  nontserver/routes/nontSitters.js
  nontserver/routes/reservation.js
  nontserver/routes/review.js
  nontserver/routes/room.js
  nontserver/routes/shelters.js
Labels: back end, help wanted

#119 fix ShelterView calculating LoadStatus
  nontclient/src/Components/Shelter/ShelterView.js
Labels: fix, front end

#120 Update filter in Find Shelter
  nontclient/src/Components/FindShelter/FindShelter.js
  nontclient/src/Components/FindShelter/FindShelterList.js
  nontclient/src/Components/FindShelter/ShelterCard.js
  nontclient/src/Components/FindShelter/ShelterFilter/DateFilter.js
  nontclient/src/Components/FindShelter/ShelterFilter/ShelterFilter.js
  nontclient/src/Components/FindShelter/StarRating.js
  nontclient/src/Services/ShelterService.js
  nontserver/Controllers/ShelterController.js
Labels: back end, front end, update

#122 Fix the rendering when "distance == 0" in Find Shelter
  nontclient/src/Components/FindShelter/ShelterCard.js
Labels: fix, front end

#129 set up openapi 3.0
  nontserver/openapi/openapi.yaml
  nontserver/openapi/room.yaml
  nontserver/openapi/schema.yaml
Labels: back end, documentation

#138 Swagger OpenAPI for NontOwner and NontSitter (First Half)
  nontclient/src/Components/Registration/Registration.js
  nontserver/Controllers/NontOwnerController.js
  nontserver/Controllers/NontSitterController.js
  nontserver/openapi/NontOwnerRoute.yaml
  nontserver/openapi/NontOwnerSchema.yaml
  nontserver/openapi/NontSitterRoute.yaml
  nontserver/openapi/NontSitterSchema.yaml
  nontserver/openapi/openapi.yaml
Labels: back end, documentation, fix, update

#153 [CI] set up CI
  .github/workflows/node.yaml
  nontserver/.github/workflows/node.yaml
  nontserver/package.json
Labels: new feature

#158 [front] fix axios bug
  nontclient/src/Services/AdminService.js
  nontclient/src/Services/CheckService.js
  nontclient/src/Services/NontService.js
  nontclient/src/Services/RegisterService.js
  nontclient/src/Services/ReserveService.js
  nontclient/src/Services/ReviewService.js
  nontclient/src/Services/RoomService.js
  nontclient/src/Services/SettingService.js
  nontclient/src/Services/ShelterService.js
  nontserver/test/LoginAndSignup/NontSitterUpdate.test.js
Labels: bug, fix, front end

#166 Sakon auth and test
  nontclient/src/Components/Payment/QRcode.js
  nontserver/package.json
  nontserver/test/LoginAndSignup/Admin.test.js
  nontserver/test/LoginAndSignup/NontOwner.test.js
  nontserver/test/LoginAndSignup/NontOwnerUpdate.test.js
  nontserver/test/LoginAndSignup/NontSitter.test.js
  nontserver/test/LoginAndSignup/NontSitterUpdate.test.js
Labels: back end

#167 Authenticate nont owner and nont sitter
  nontserver/routes/nontOwners.js
  nontserver/routes/nontSitters.js
  nontserver/test/LoginAndSignup/NontOwner.test.js
  nontserver/test/LoginAndSignup/NontOwnerUpdate.test.js
  nontserver/test/LoginAndSignup/NontSitterUpdate.test.js
  nontserver/test/Shelter/FindShelter.test.js
Labels: back end, documentation

#177 Nontification
  nontserver/Controllers/InterfaceController.js
  nontserver/Controllers/PaymentController.js
  nontserver/Controllers/ReservationController.js
  nontserver/Notification/CancelNotification.js
  nontserver/Notification/NotificationController.js
  nontserver/Notification/NotificationInterface.js
  nontserver/Notification/PaymentNotification.js
  nontserver/Notification/ReserveNotification.js
  nontserver/package.json
  nontserver/yarn.lock
Labels: back end, new feature
